name: Application build with Maven, create and publish Docker image, verify result 

on:
  push:
    branches:
    - main

jobs:
  maven: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build with Maven
      run: ./mvnwpackage

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker:
    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Logging in to Docker
      run: docker login ghcr.io -u hermanbence -p ${{ github.token }}

    - name: Build the Docker image
      run: docker build . -t ghcr.io/hermanbence/cubix/1/homework/app:springboot

    - name: Publishing the Docker image
      run: docker push ghcr.io/hermanbence/cubix/1/homework/app:springboot

  docker-verify :
    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Verify Docker image 
      run: ./verify-image.sh
